### ISSUE TITLE
Parser/Tokenizer Defined in YAML Files

### ISSUE THREAD

**Issue by johneastman** [johneastman/boomerang#6]
# Goal
Define the parser and tokenizer in YAML files. The tokenizer already partially does this in `tokens/tokens.yaml` (although it doesn't handle strings, numbers (integers and floats), or identifiers).

# Background Info
`tokens/tokens.yaml` looks like this:
```yaml
tokens:
  keywords:
    - literal: set
      name: SET
      type: SET
    - literal: func
      name: FUNCTION
      type: FUNCTION
  ...
  symbols:
    - literal: '.'
      name: PERIOD
      type: PERIOD
    - literal: '='
      name: ASSIGN
      type: ASSIGN
  ...
  data_types:
    - literal: ''
      name: EOF
      type: EOF
    - literal: ''
      name: INTEGER
      type: INTEGER
  ...
```

Not only is this file used by the tokenizer, but it could also use this file to auto-generate a README that displays keywords, symbols, and datatypes. I would like to do something similar for the parser, where a yaml file defines the structure, and we also use it to generate a grammar or add info to a README. The file might look something like this:
```yaml
program:
  statements:
    - name: Set
       tokens:
         - type: SET
         - type: IDENTIFIER
         - type: ASSIGN
         - type: expression
  expressions:
    - name: BinaryExpression
       tokens:
         - type: factor
         - type: PLUS
         - type: factor
  factors:
    - name: Integer
       tokens:
        - type: INTEGER
    - name: Float
       tokens:
         - type: FLOAT
```

# Challenges
* Parsing BinaryExpressions with this structure
* Handling AST types that call themselves (e.g., an expression where one of the tokens is an expression (infinite loop))
